import { playerType } from "../../types/PlayerType";

export const dummyPlayers: playerType[] = [
  {
    name: "Sanni Yusuf",
    alias: "Buch",
    playerQuote: "Get your head in the game",
    positions: ["RW", "DM", "FWD"],
    favoritePosition: "Midfielder",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "google.com",
      instagram: "ratsass.com",
      twitter: "infinity.ccom",
    },
    stats: {
      legacyGoals: 4,
      futureStats: [
        {
          season: "2023A",
          goals: 9,
          assists: 13,
          cleanSheets: 3,
          yellowCards: 9,
          redCards: 0,
        },
      ],
    },
  },
  {
    name: "Oghenetega Esedere",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "a",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "b",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "ccccccccc",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "ddddd",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "eeeee",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "fffff",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "gggg",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "hhh",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "iii",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "jjj",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "kkkk",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "lllll",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "mmmmmm",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "ooooo",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "ppppp",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "qqqqq",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "ssssss",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "ttttt",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "uuuuuu",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "vvvvvv",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "wwwww",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "xxxxx",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "yyyyy",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "zzzz",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "azsza",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "fgtrbrtb",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "ytntyimiu,u",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "ghghghshsrst",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "abaab",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "ggbnmm",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "werty",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "yuiop",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "asdfgh",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "xccvbnm",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "vvbbnn",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
  {
    name: "mmkkll",
    alias: "Tega",
    playerQuote: "Groove on man",
    positions: ["CB", "DM", "GK"],
    favoritePosition: "Defender",
    image: { public_id: "No Image", url: "No Image" },
    socialMedia: {
      facebook: "linkin.com",
      instagram: "screwyouIhateyou.com",
      twitter: "nawhywedeycallamgoat.ccom",
    },
    stats: {
      legacyGoals: 89,
      futureStats: [
        {
          season: "2023A",
          goals: 85,
          assists: 13,
          cleanSheets: 2,
          yellowCards: 3,
          redCards: 4,
        },
      ],
    },
  },
];
